### PR TITLE
Update react-native-linear-gradient to 37aadbd3739b90d199a01aeb108422ecd67ad67f

### PR DESCRIPTION
**Pull request by oguzkocer**

### CODE REVIEW

**Comment by oguzkocer** [comment]
@illusaen This seems to be using the `wp-fork` branch now. Shouldn't that be set to a specific tag instead? I am a little worried about using a branch like this as it can be harder to track a change.

cc @mchowning in case you have some ideas as well.

**Comment by illusaen** [comment]
So I went by [SO's answer](https://stackoverflow.com/questions/16350673/depend-on-a-branch-or-tag-using-a-git-url-in-a-package-json) which seems to imply it works for both
Screen Shot 2021-08-19 at 2 58 32 PM
but if you could confirm, Matt, that would be great.

**Comment by oguzkocer** [comment]
To be clear, I am not worried about it working or not, I am sure it works. I am worried that if `react-native-linear-gradient`'s `wp-fork` branch is updated, these changes will be applied to this library even if we didn't want to. It's the difference between using a `SNAPSHOT` version (which is what this PR merged) and using a tag.

Fwiw, we don't use `SNAPSHOT` versions in our release pipelines, for any Android project, as far as I know.

**Comment by mchowning** [comment]
> I am worried that if react-native-linear-gradient's wp-fork branch is updated, these changes will be applied to this library even if we didn't want to.

👍  to what @oguzkocer said. We want to be referencing a tag, not the branch.

**Comment by mchowning** [comment]
Just following up on this. I see that we've added `wp-fork` tags to all the repos, which I'm guessing is why that's what we're referencing both here and in the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/34048/files#diff-1f256578dd9ab8dda6c3913a55a588312129f3404bb0cdf0b1ab52f0a6937119R34). The problem is that having a tag that is exactly the same as a branch is at best confusing. When both a tag and a branch exist on different commits in a repo, my testing shows that npm is pulling down the branch, not the tag. So I think @oguzkocer 's concern is right.

In my opinion, we need to remove all the `wp-fork` tags from the forked repos (just to avoid confusion between the fork and the tag with the same name, even git got confused in my testing) and add a unique tag to all the `wp-fork` branches. Perhaps something like `wp-fork-tag-1`.

**Comment by illusaen** [comment]
> Just following up on this. I see that we've added `wp-fork` tags to all the repos, which I'm guessing is why that's what we're referencing both here and in the [Gutenberg PR](https://github.com/WordPress/gutenberg/pull/34048/files#diff-1f256578dd9ab8dda6c3913a55a588312129f3404bb0cdf0b1ab52f0a6937119R34). The problem is that having a tag that is exactly the same as a branch is at best confusing. When both a tag and a branch exist on different commits in a repo, my testing shows that npm is pulling down the branch, not the tag. So I think @oguzkocer 's concern is right.
> 
> In my opinion, we need to remove all the `wp-fork` tags from the forked repos (just to avoid confusion between the fork and the tag with the same name, even git got confused in my testing) and add a unique tag to all the `wp-fork` branches. Perhaps something like `wp-fork-tag-1`.

Ahhhh I see. That makes sense, I was thinking that once the branch got merged it would default to the tag.

**Comment by mchowning** [comment]
Can you work on this on Monday @illusaen ? Feel free to touch base with me and we can split up the work to knock it out faster. 🙂

**Pull request merged**
